### ISSUE TITLE
Can't compile boost 1.69.0 with ndk r18b

### ISSUE THREAD

**Issue by jpo38** [dec1/Boost-for-Android#17]
I'm getting lots of different errors when trying to do this, I posted them here:
https://stackoverflow.com/questions/54323831/how-to-build-boost-1-69-0-for-android-with-ndk-r18b-using-dec1-boost-for-android

**Comment by dec1** [comment]
Hello.

Sorry, only building on linux is officially supported. Mac and Windows should work fine too but details of setting up the relevant environments (eg cgwin or homebrew) is beyond the scope of what this project tries to do. See also [here](
https://github.com/dec1/Boost-for-Android/issues/6#issuecomment-337257137).

If you want to use  windows as a host you have two easiest options are:

- Use virtual machines eg. [VirtualBox](https://www.virtualbox.org) or and create a linux virtual machine where you do the building.

- You can also simply download and use the precompiled binaries I have made [available](https://github.com/dec1/Boost-for-Android/releases)

No matter what os you use to build under, the resulting binaries can then be copied to windows and used from then on as if you had built on windows to start with (theyre cross compiled for android).

**Comment by jpo38** [comment]
Thanks for the reply.

Unfortunately, your precompiled binaries are "shared" and I need them "static".

Using a virtual machine could be an option.

Thanks

**Comment by dec1** [comment]
Ok.

If you have any problems, I should be building more binaries (with ndk 19) soon. I can see about including static versions too (but there's generally less demand for them, since its harder to avoid conflicts - see eg [here](https://developer.android.com/ndk/guides/cpp-support#static_runtimes))

Good luck

**Comment by jpo38** [comment]
Thanks, I'm really targetting r18b, so I need to find a way to compile this.

**Comment by jpo38** [comment]
However, including static libraries to your builds may be a good option. There's a lot of boost binaries and it's easier to have them linked statically.

**Comment by dec1** [comment]
Thanks for the helpful instructions.

moritz-wundke/Boost-for-Android is a great project and the initial Boost-for-Android. However, the way it works, it requires constant maintenance in order to support each new combination of the ndk and boost as new versions come out (you can only build for the explicit versions the project has been configured to support). After a long time (boost version 1.53 -> 1.63, and ndk 10->16) where its seemed like the project was no longer being maintained, and I got no replies to emails, from the maintainer as to the status, I decided to fork it, which is why dec1/Boost-for-Android came into existence.

It has the advantage that it does not, in general, need to be updated to support new versions of google's ndk, or boost. They generally build out of the box, or need rare adjustments (but I still test regularly to make sure).

Using dec1/Boost-for-Android is arguably also a lot simpler (certainly than following your instructions above). You can build for any/all architectures (arm64-v8a, armeabi-v7a, x86, x86_64), in one go in a single line of code. And if you dont need a custom build you can simply download prebuilt binaries (boost 1.69.0, with ndk 19 and 18b, both dynamic and static are now also available) from here

Im pretty sure that it could be made to work on windows or mac too (possibly with less effort than you spent above), but its a lot easier to just use a virtual machine (eg the free virtualbox) to do the build, and copy the resulting binaries to windows if you really want to develop there.

Nonetheles, moritz-wundke/Boost-for-Android seems to have gotten a new influx of contributions of late, which is good news for everybody. And if you find it more suitable for building boost on windows (or any other platform) then thats great.

Good luck with your projects and thanks again for the insights.
